name: Indent

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: DoozyX/clang-format-lint-action@v0.13
      with:
        source: '.'
        exclude: './src/thirdparty/*'
        extensions: 'hpp,cpp'
        clangFormatVersion: 12
        inplace: true
    - run: |
        git diff
        git diff-files --quiet || exit $?
